---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      cleanup: true
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - vscode.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
    install:
      install-weak-deps: false
      packages:
        - code
        - distrobox
        - tailscale
        - zsh
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-tour
        - malcontent-control # Parental Controls UI frontend
        - toolbox
        - yelp

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - com.brave.Browser
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.ranfdev.DistroShelf
          - com.rustdesk.RustDesk
          - com.spotify.Client
          - io.github.flattool.Warehouse
          - org.cryptomator.Cryptomator
          - org.mozilla.firefox

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
